### ISSUE TITLE
Override past vs next game?

### ISSUE THREAD

**Issue by LCMilstein** [D34DC3N73R/ha-nfl-card#1]
This is AWESOME. I have the card in a test dash right now and it's Tuesday, so I'm seeing the post-game view. 

Is there a way to manually force it to move to the pre-game view? 

Alternatively, is there a way to support secondary info?

**Comment by D34DC3N73R** [comment]
This card relies on data from the HA-NFL integration (and similar forks). And they rely on data from the ESPN json API. ESPN updates the API on Tuesday night or Wednesday morning depending on where you are at. Unfortunately, we can only show what ESPN provides.

I'm not entirely sure what you mean by secondary info, but you can set up another sensor using the HA-NFL integration (or similar forks) and have multiple scoreboards displayed with no problem.

**Comment by D34DC3N73R** [comment]
I'm going to close this, but feel free to reach out if you have any other issues.
