### ISSUE TITLE
Repository structure for v0.3.7 is not compliant

### ISSUE THREAD

**Issue by dh34992** [D34DC3N73R/ha-nfl-card#2]
Trying to add to HACS and receive the following error.   

<Integration D34DC3N73R/ha-nfl-card> Repository structure for v0.3.7 is not compliant

I'm running the following version of HA on Raspberry Pi 4B
Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by D34DC3N73R** [comment]
Are you choosing "Lovelace" as the repository category? Also the full repo URL `https://github.com/D34DC3N73R/ha-nfl-card` ?

**Comment by dh34992** [comment]
Ahh!!  My apologies.  I did not select Lovelace.  It is working now as expected. Thank you!!

**Comment by D34DC3N73R** [comment]
NP, good luck this season!
