### ISSUE TITLE
Getting a "custom element doesn't exist: nfl-card" error message for the NFL Card

### ISSUE THREAD

**Issue by Spiffieman** [D34DC3N73R/ha-nfl-card#7]
Hi there - love your card, have been using it for the past year or so, and noticed that it stopped working in HASS for me over one of the past HASS version updates. I am currently on 2023.10.2 and Hass OS 10.4 and the NFL-Card version .83. 

I noticed the above error message on my dashboard. So I confirmed everything looked correct, the repo was still in as a custom repo in HACs, the files were in the correct directory, and I have the custom element added (nothing changed). 

I decided to uninstall and delete everything (HACS Custom Card + custom element) and reinstalled the custom card and when I did that, I noticed the URL was automatically added to custom elements but the URL is showing as "/hacsfiles/ha-nfl-card/ha-nfl-card.js?hacstag=411167091038" instead of what is listed in your instructions (/hacsfiles/ha-nfl-card/ha-nfl-card.js). After this, the card still isn't loading. 

So I edited the URL that had the extra stuff at the end and made it match your instructions. 

Card still isn't loading. 

Then manually downloaded the card to see if that would change anything and it didn't. 

Any thoughts? 

![image](https://github.com/D34DC3N73R/ha-nfl-card/assets/76534297/5aee7499-d217-493a-964d-878b5c6d728c)
![image](https://github.com/D34DC3N73R/ha-nfl-card/assets/76534297/9b3262a4-13ab-40b5-89dc-fc814f338706)
![image](https://github.com/D34DC3N73R/ha-nfl-card/assets/76534297/a64ea478-041f-40e6-b375-be17d70c0946)
![image](https://github.com/D34DC3N73R/ha-nfl-card/assets/76534297/9bc02c04-0b22-4992-93c1-bc7d9b869638)

**Comment by gonzotek** [comment]
It started happening to me too and I've been looking at this a bit today.  I think something may have happened with unpkg.com, I'm seeing a 500 error for the lit-element module import in the browser console.  I think that's what's preventing ha-nfl-card from loading.  I don't know enough about building/packaging cards to resolve it, but I'm guessing if we could get the lit-element source and manually package it into the card source, we wouldn't have to depend on unpkg . 
Apparently module imports are experimental:
From https://unpkg.com/
> ?module
> Expands all [“bare” import specifiers](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier) in JavaScript modules to unpkg URLs. This feature is very experimental

I could be way off on all of these guess!

**Comment by D34DC3N73R** [comment]
try updating to the "main" branch instead of a version number. If that works let me know and I'll push a new release.

**Comment by gonzotek** [comment]
Just changed over to 'main' in hacs and all looks good again!  Thanks!

**Comment by D34DC3N73R** [comment]
This is fixed in v0.3.9
